<?php

namespace ContainerCRtU8BK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HvFfM2bService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hvFfM2b' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hvFfM2b'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CategoriaController::delete' => ['privates', '.service_locator.DqpYpEE', 'get_ServiceLocator_DqpYpEEService', true],
            'App\\Controller\\CategoriaController::edit' => ['privates', '.service_locator.DqpYpEE', 'get_ServiceLocator_DqpYpEEService', true],
            'App\\Controller\\CategoriaController::index' => ['privates', '.service_locator..VtoRNe', 'get_ServiceLocator__VtoRNeService', true],
            'App\\Controller\\CategoriaController::show' => ['privates', '.service_locator.DqpYpEE', 'get_ServiceLocator_DqpYpEEService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\CategoriaController:delete' => ['privates', '.service_locator.DqpYpEE', 'get_ServiceLocator_DqpYpEEService', true],
            'App\\Controller\\CategoriaController:edit' => ['privates', '.service_locator.DqpYpEE', 'get_ServiceLocator_DqpYpEEService', true],
            'App\\Controller\\CategoriaController:index' => ['privates', '.service_locator..VtoRNe', 'get_ServiceLocator__VtoRNeService', true],
            'App\\Controller\\CategoriaController:show' => ['privates', '.service_locator.DqpYpEE', 'get_ServiceLocator_DqpYpEEService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\CategoriaController::delete' => '?',
            'App\\Controller\\CategoriaController::edit' => '?',
            'App\\Controller\\CategoriaController::index' => '?',
            'App\\Controller\\CategoriaController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CategoriaController:delete' => '?',
            'App\\Controller\\CategoriaController:edit' => '?',
            'App\\Controller\\CategoriaController:index' => '?',
            'App\\Controller\\CategoriaController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
