<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'categoria_index' => [[], ['_controller' => 'App\\Controller\\CategoriaController::index'], [], [['text', '/categoria/']], [], []],
    'categoria_new' => [[], ['_controller' => 'App\\Controller\\CategoriaController::new'], [], [['text', '/categoria/new']], [], []],
    'categoria_show' => [['id'], ['_controller' => 'App\\Controller\\CategoriaController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/categoria']], [], []],
    'categoria_edit' => [['id'], ['_controller' => 'App\\Controller\\CategoriaController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/categoria']], [], []],
    'categoria_delete' => [['id'], ['_controller' => 'App\\Controller\\CategoriaController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/categoria']], [], []],
    'produto_index' => [[], ['_controller' => 'App\\Controller\\ProdutoController::index'], [], [['text', '/produto/']], [], []],
    'produto_new' => [[], ['_controller' => 'App\\Controller\\ProdutoController::new'], [], [['text', '/produto/new']], [], []],
    'produto_show' => [['id'], ['_controller' => 'App\\Controller\\ProdutoController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/produto']], [], []],
    'produto_edit' => [['id'], ['_controller' => 'App\\Controller\\ProdutoController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/produto']], [], []],
    'produto_delete' => [['id'], ['_controller' => 'App\\Controller\\ProdutoController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/produto']], [], []],
];
